# <center>Deep Learning (Artificial Neural Network)</center>

# Regression

### Importing the libraries

In [81]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [82]:
tf.__version__

'2.19.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [85]:
dataset = pd.read_csv('Folds5x2_pp.csv')
dataset


AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [86]:
X = dataset.iloc[:, :-1].values


In [87]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [88]:
y = dataset.iloc[:, -1].values

In [89]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [91]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [94]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [96]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [98]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [100]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [103]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [105]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 12s 13ms/step - loss: 75856.2656
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 178.6241
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 174.4789
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 173.0500
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 166.6637
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 166.4320
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 157.6040
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 147.2914
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 140.5373
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 135.0918
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 123.6234
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 114.1612
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 104.0708
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 95.8806
Epoch 15/10

### Predicting the results of the Test set

In [107]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
[[429.2  431.23]
 [460.27 460.01]
 [463.85 461.14]
 ...
 [470.9  473.26]
 [438.04 438.  ]
 [457.08 463.28]]


# <center>Thank You </center>